In [1]:
import torch

In [5]:
tensor1 = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
print(tensor1)
print(tensor1.ndim)
print(tensor1.shape)
print(tensor1[0])

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
3
torch.Size([1, 3, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [6]:
tensor2 = torch.tensor([[[[5, 6, 7], [11, 45, 7], [22, 91, 2], [11, 55, 69]]]])
tensor2

tensor([[[[ 5,  6,  7],
          [11, 45,  7],
          [22, 91,  2],
          [11, 55, 69]]]])

In [8]:
tensor2.ndim

4

In [10]:
tensor2.shape

torch.Size([1, 1, 4, 3])

In [13]:
tensor3 = torch.tensor([[[[5, 6, 7], [11, 45, 7]],[[11, 55, 69], [22, 91, 2]]]])
tensor3

tensor([[[[ 5,  6,  7],
          [11, 45,  7]],

         [[11, 55, 69],
          [22, 91,  2]]]])

In [15]:
tensor3.ndim

4

In [26]:
print(tensor3.shape)
print(tensor3[0][1])
print(tensor3[0][1][0])
print(tensor3[0][1][0][2])
print(tensor3[0][1][0][2].item())

torch.Size([1, 2, 2, 3])
tensor([[11, 55, 69],
        [22, 91,  2]])
tensor([11, 55, 69])
tensor(69)
69


In [37]:
tensor4 = torch.tensor([[[[5, 6, 7], [11, 45, 7]],[[11, 55, 69], [22, 91, 2]]],[[[-2, -6, -32], [-1, -85,-9]],[[-101, -5, -99], [-2, -91, -3]]]])
tensor4

tensor([[[[   5,    6,    7],
          [  11,   45,    7]],

         [[  11,   55,   69],
          [  22,   91,    2]]],


        [[[  -2,   -6,  -32],
          [  -1,  -85,   -9]],

         [[-101,   -5,  -99],
          [  -2,  -91,   -3]]]])

In [30]:
tensor4.ndim

4

In [32]:
tensor4.shape

torch.Size([2, 2, 2, 3])

In [41]:
tensor4[1][1][1].item() #item() can be used for tensors with 1 element

RuntimeError: a Tensor with 3 elements cannot be converted to Scalar

In [42]:
tensor4[1][1][1][2]

tensor(-3)

In [43]:
tensor4[1][1][1][2].item()

-3

In [39]:
tensor5 = torch.tensor([[[1.3,2.2,3.88],[4.212121,5.434343,6.11],[7.265465262,8,9]]])
tensor5

tensor([[[1.3000, 2.2000, 3.8800],
         [4.2121, 5.4343, 6.1100],
         [7.2655, 8.0000, 9.0000]]])